#!/usr/bin/env bash

# Get the current shell
# current_shell=$(ps -p $$ -ocomm=)
current_shell=$(basename "$SHELL")


# Check if the first argument is passed, otherwise set it to 'install'
action=${1:-install}

# Get the directory of the script to run the appropriate script
dotfiles=$(dirname "$(realpath "$0")")
mkdir -p "$dotfiles/bak"

#  Update the DOTROOT variable in the zshrc file
if [ -f "$dotfiles/zshrc" ]; then
  sed -i "s|^export DOTROOT=.*|export DOTROOT=\"$dotfiles\"|" "$dotfiles/zshrc"
fi
#  Update the DOTROOT variable in the bashrc file
if [ -f "$dotfiles/bashrc" ]; then
  sed -i "s|^export DOTROOT=.*|export DOTROOT=\"$dotfiles\"|" "$dotfiles/bashrc"

# Run the appropriate script based on the current shell
case $current_shell in
  *bash|*zsh)
    echo "Detected $current_shell shell. Running install_bash.sh with argument '$action'..."
    $current_shell "$dotfiles/bin/install_bashdots" "$action"
    ;;
  *)
    echo "Detected $current_shell shell. Running install_posix.sh with argument '$action'..."
    $current_shell "$dotfiles/bin/install_posixdots" "$action"
    ;;
esac
fi

exec "${SHELL}"