" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.config/vimrc/my_configs.vim

set runtimepath+=~/.config/vimrc

source ~/.config/vimrc/vimrcs/basic.vim
source ~/.config/vimrc/vimrcs/filetypes.vim
"source ~/.config/vimrc/vimrcs/plugins_config.vim
source ~/.config/vimrc/vimrcs/extended.vim
try
  source ~/.config/vimrc/my_configs.vim
catch
endtry
