#!/bin/bash

 #while true; do
	echo  $image
    killall wallengine
    image=~/Games/Steam/steamapps/workshop/content/431960/$(ls ~/Games/Steam/steamapps/workshop/content/431960/ | shuf -n 1)
	 ~/dotfile/config/wallengine/wallpaperengine/build/wallengine \
        --silent  \
         --screen-root eDP-1 \
         --assets-dir ~/Games/Steam/steamapps/common/wallpaper_engine/assets \
         --fps 30 \
         $image   &
#	sleep 29m
# done
# sleep 1m
