#!/usr/bin/bash

#start swwww
swww query || swww init

#figure out which waybar theme is set
THEMEIS=$(readlink -f ~/.config/hypr/waybar/style/style.css | cut -d '-' -f2)

#show the correct wallpapper based on the theme
if [ $THEMEIS == "style-dark.css" ]; then
    swww img ~/.config/hypr/bg/08.jpg
else
    swww img ~/.config/hypr/bg/portal.png
fi 
