# /etc/portage/bashrc
post_pkg_postinst() {
    if [[ ${PN} == "grub" ]]; then
        elog "Re-install grub and Re-mkconfig grub."
        grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=GRUB
        grub-mkconfig -o /boot/grub/grub.cfg
    fi
}
